---
- name: "Include os specific variables for RedHat hosts"
  ansible.builtin.include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: "Ensure Dependencies Are Installed On Red Hat <= 7 host"
  ansible.builtin.yum:
    name: "{{ dependency_list }}"
    state: present
    update_cache: true
  when: ansible_distribution_major_version | int <= 7

- name: "Ensure Dependencies Are Installed On Red Hat >= 8 host"
  ansible.builtin.dnf:
    name: "{{ dependency_list }}"
    state: present
    allowerasing: true
    update_cache: true
  when: ansible_distribution_major_version | int >= 8

- name: "Upgrade Red Hat <= 7 host"
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_distribution_major_version | int <= 7

- name: "Upgrade Red Hat >= 8 host"
  ansible.builtin.dnf:
    name: '*'
    state: latest
    allowerasing: true
    update_cache: true
  when: ansible_distribution_major_version | int >= 8
