---
- name: "Include os specific variables for Debian hosts"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "Update cache on Debian based host"
  ansible.builtin.apt:
    update_cache: true

- name: "Ensure Dependencies Are Installed On Debian host"
  ansible.builtin.apt:
    name: "{{ dependency_list }}"
    update_cache: true
    autoremove: true
    state: present

- name: "Upgrade Debian host"
  ansible.builtin.apt:
    upgrade: 'full'
    update_cache: true
    autoremove: true
    state: latest
  register: packages

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ packages }}"
